title: 3D Model Generator
description: Convert CAD files to 3D models with AI-powered processing
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
baseurl: ""
url: "https://shankarelavarasan.github.io"

# GitHub Pages settings
github:\  repository_url: https://github.com/shankarelavarasan/3d_model_generator

# Ensure index.md takes precedence over index.html
readme_index:
  remove_originals: true
  with_frontmatter: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .bundle/
  - .jekyll-metadata
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - assets/css/style.scss